version: '3.6'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: users 
  
  appirest:
    build: .
    container_name: appirest
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node-modules